language: java
sudo: true
# dist: trusty

os:
   - ubuntu
  
jdk:
   - openjdk8

install:
   - mvn -q clean install -DskipTests=true -Dmaven.javadoc.skip=true 

script:
   - touch log.txt
   # object construction
   - mvn -q -Dtest=ComputationGraphConstructionTest test -pl shell <log.txt
   # test legitimization
   - mvn -q -Dtest=TestLegitimizationTest test -pl shell <log.txt
   #- mvn -Dtest=LayeredCallExampleTest test -pl EvosuiteTest -e
   #- mvn -Dtest=MultipleConstructorsExampleTest test -pl EvosuiteTest -e
   #- mvn -Dtest=MultipleExceptionsExampleTest test -pl EvosuiteTest -e
   # fbranch
   #- mvn -Dtest=ValueRangeExampleTest test -pl EvosuiteTest -e
   # smart mutation
   #- mvn -Dtest=StringArrayExampleTest test -pl EvosuiteTest -e
   # object construction
   #- mvn -Dtest=CascadingCallExampleTest test -pl EvosuiteTest -e
