language: java
sudo: true
# dist: trusty

os:
   - ubuntu
  
jdk:
   - openjdk8

install:
   - mvn clean install -DskipTests=true -Dmaven.javadoc.skip=true -B

script:
   # object construction
   - mvn -Dtest=ComputationGraphConstructionTest test -pl shell -e
   # test legitimization
   - mvn -Dtest=TestLegitimizationTest test -pl shell -e
   #- mvn -Dtest=LayeredCallExampleTest test -pl EvosuiteTest -e
   #- mvn -Dtest=MultipleConstructorsExampleTest test -pl EvosuiteTest -e
   #- mvn -Dtest=MultipleExceptionsExampleTest test -pl EvosuiteTest -e
   # fbranch
   #- mvn -Dtest=ValueRangeExampleTest test -pl EvosuiteTest -e
   # smart mutation
   #- mvn -Dtest=StringArrayExampleTest test -pl EvosuiteTest -e
   # object construction
   #- mvn -Dtest=CascadingCallExampleTest test -pl EvosuiteTest -e
