language: java
sudo: true
# dist: trusty

os:
   - Linux 
jdk:
   - openjdk8
before_install: sudo echo "MAVEN_OPTS='-Xmx2048m -Xms1024m -Dorg.slf4j.simpleLogger.defaultLogLevel=error'" > ~/.mavenrc
install:
   - mvn -q clean install -DskipTests=true -Dmaven.javadoc.skip=true 
script:
#    # object construction
    - mvn -q -Dtest=ComputationGraphConstructionTest test -pl shell 
#    # test legitimization
    - mvn -q -Dtest=TestLegitimizationTest test -pl shell 
   #- mvn -Dtest=LayeredCallExampleTest test -pl EvosuiteTest -e
   #- mvn -Dtest=MultipleConstructorsExampleTest test -pl EvosuiteTest -e
   #- mvn -Dtest=MultipleExceptionsExampleTest test -pl EvosuiteTest -e
   # fbranch
   #- mvn -Dtest=ValueRangeExampleTest test -pl EvosuiteTest -e
   # smart mutation
   #- mvn -Dtest=StringArrayExampleTest test -pl EvosuiteTest -e
   # object construction
   #- mvn -Dtest=CascadingCallExampleTest test -pl EvosuiteTest -e
env:
   global:
      - MAVEN_OPTS: "-Xmx2048m -Xms1024m -Dorg.slf4j.simpleLogger.defaultLogLevel=error"
sudo: required
cache:
  directories:
    - $HOME/.m2 
