language: java
sudo: true
# dist: trusty

os:
   - Linux 
jdk:
   - openjdk8
install:
   - mvn -q clean install -DskipTests=true -Dmaven.javadoc.skip=true 
script:
#    # object construction
    - mvn -q -Dtest=ComputationGraphConstructionTest test -pl shell  > ~/.log
#    # test legitimization
    - mvn -q -Dtest=TestLegitimizationTest test -pl shell  > ~/.log
   #- mvn -Dtest=LayeredCallExampleTest test -pl EvosuiteTest -e
   #- mvn -Dtest=MultipleConstructorsExampleTest test -pl EvosuiteTest -e
   #- mvn -Dtest=MultipleExceptionsExampleTest test -pl EvosuiteTest -e
   # fbranch
   #- mvn -Dtest=ValueRangeExampleTest test -pl EvosuiteTest -e
   # smart mutation
   #- mvn -Dtest=StringArrayExampleTest test -pl EvosuiteTest -e
   # object construction
   #- mvn -Dtest=CascadingCallExampleTest test -pl EvosuiteTest -e
cache:
  directories:
    - $HOME/.m2 
